# 1. The URL from the JDBC tab in Supabase
spring.datasource.url=jdbc:postgresql://db.qmoajyxoedlmderxarfa.supabase.co:6543/postgres

# 2. Always 'postgres' unless you changed it
spring.datasource.username=postgres

# 3. The password you created when you made the Supabase project
spring.datasource.password=Latinhonorscutieee_5

# 4. The Magic Command to create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


